Application has thrown an uncaught exception and is terminated:
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (C:\Users\Andre\Documents\My Web Sites\NQ2\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:553:74)
    at EventEmitter.emit (events.js:106:17)
    at null.<anonymous> (C:\Users\Andre\Documents\My Web Sites\NQ2\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:140:15)
    at EventEmitter.emit (events.js:98:17)
    at Socket.<anonymous> (C:\Users\Andre\Documents\My Web Sites\NQ2\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:512:10)
    at Socket.EventEmitter.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:415:13)
